<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_searchbox_other</name>
   <tag></tag>
   <elementGuidId>bf9abf8e-a562-4352-b522-f169be957332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;RENTAL_DROPOFF_LOCATION&quot;]/div/div/div[5]/div[2]/div/div/div[1]/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
